insert into guru.work (id,name, author) values (3,'Science of Being and Art of Living', 'Maharishi Mahesh Yogi');
insert into guru.quote (workid,content) values (3,'Assuming a subjective nature, Being becomes mind; assuming an objective nature, It becomes matter.');
insert into guru.quote (workid,content) values (3,'Expansion of happiness is the purpose of creation.');
insert into guru.quote (workid,content) values (3,'it is certainly possible to glorify the field of Karma by the light of Being.');
insert into guru.quote (workid,content) values (3,'The skill in action is to first bring the activity to nil, and from there start to act.');
insert into guru.quote (workid,content) values (3,'It is possible for a man to live in the field of action and yet simultaneously live a life of eternal freedom in the bliss consciousness of absolute Being.');
insert into guru.quote (workid,content) values (3,'It is open to every individual to experience this state of Being and create in his life a state of eternal freedom while bringing greater success in all fields of activity.');
insert into guru.quote (workid,content) values (3,'The experiencer and the object of experience are both relative. When we have transcended the field of the experience of the subtlest object, the experiencer is left by himself without an experience, without an object of experience, and without the process of experiencing. When the subject is left without an object of experience, having transcended the subtlest state of the object, the experiencer steps out of the process of experiencing and arrives at the state of Being.');
insert into guru.quote (workid,content) values (3,'Thinking, in itself, is the subtle state of speech.');
insert into guru.quote (workid,content) values (3,'How it is technically achieved is a matter of personal instruction from those who have been trained to impart this technique of experiencing Being.');
insert into guru.quote (workid,content) values (3,'The whole universe is influenced by every thought, word, and action of every individual.');
insert into guru.quote (workid,content) values (3,'Because each personality has its own quality, it is extremely necessary that each man should have selected for him a special quality of thought whose physical influence will be conducive and useful to himself and the world at large.');
insert into guru.quote (workid,content) values (3,'The mind, the body, and the surroundings are the three main spheres of life.');
insert into guru.quote (workid,content) values (3,'Similarly, in the life of the individual we find that inner Being is unmanifested absolute Being which manifests as the ego, intellect, mind, senses, and Pra?a. All these subtle states of life make up the inner man or the subject within, the subjective aspect of life. The subjective aspect of life differs from the objective aspect of life, which is the body in all its various attributes.');
insert into guru.quote (workid,content) values (3,'The purpose of individual life is also the purpose of the life of the entire cosmos. The purpose of creation is expansion of happiness which is fulfilled through the process of cosmic evolution.');
insert into guru.quote (workid,content) values (3,'If one is not happy, one has lost the very purpose of life.');
insert into guru.quote (workid,content) values (3,'Man’s nervous system is the most highly evolved. Therefore, the scope of evolution of man is unlimited in this life.');
insert into guru.quote (workid,content) values (3,'The nervous system is developed to the extent that through proper activity (the revelation of which is the purpose of this book) the man can contact absolute bliss, creativity, intelligence, power, and energy.');
insert into guru.quote (workid,content) values (3,'To live a life of freedom is the purpose of life in the human species.');
insert into guru.quote (workid,content) values (3,'The normal standard of human life is a life of all glory in the material field of the world, supplemented by the eternal freedom in God Consciousness.');
insert into guru.quote (workid,content) values (3,'Cosmic Consciousness is the state of normal human life, and to attain that is to begin to live a normal life.');
insert into guru.quote (workid,content) values (3,'This may only be created by each individual for himself by transforming the nature of his mind in such a way, and to such an extent, that, by nature, the mind can pick up only right thoughts and engage itself in right speech and action.4');
insert into guru.quote (workid,content) values (3,'boundaries of individual life are not restricted to the boundaries of the body, and not even to those of one’s family or one’s home; they extend far beyond that sphere to the limitless horizons of cosmic life.');
insert into guru.quote (workid,content) values (3,'the art of living requires that the mind draw the power of Being and pass it on to the body and surroundings.');
insert into guru.quote (workid,content) values (3,'The Absolute and the relative are the two phases of one’s existence. It is the art of living that brings these two together, enabling all values of life to be lived.');
insert into guru.quote (workid,content) values (3,'If a sales manager in a factory keeps making sales, the production manager keeps the factory producing. If the product is not sold, the production also comes to a standstill. Production depends upon the consumption.');
insert into guru.quote (workid,content) values (3,'The laws of nature cannot be deceived; the reaction will come. If a man is jealous of you, you will find, when you search your heart, that you have been jealous either of him or of someone else sometime in the past. Be kind to him, and the surroundings will be kind to you; be loving to him, and the surroundings will be loving to you; begin to doubt, and the surroundings begin to doubt you. If you hate, the surroundings begin to hate you. If the surroundings begin to hate you, do not blame the surroundings, blame your own inner conscience.');
insert into guru.quote (workid,content) values (3,'Therefore, in all walks of life, under all circumstances, in all types of surroundings, animate or inanimate, living or nonliving, it is necessary to have a very loving, kind, and sympathetic view in the inner core of our heart.');
insert into guru.quote (workid,content) values (3,'Thus the surroundings that are near to you are directly affected by your behavior. But surroundings that are remote from you are mostly reacting to your feelings and thoughts.');
insert into guru.quote (workid,content) values (3,'Thought waves are much more powerful than the waves of speech and action.');
insert into guru.quote (workid,content) values (3,'a normal man is a man of Cosmic Consciousness—a fully grown man is a perfectly developed personality.');
insert into guru.quote (workid,content) values (3,'conscious contact');
insert into guru.quote (workid,content) values (3,'a grand and successful attunement with the almighty power of nature.');
insert into guru.quote (workid,content) values (3,'it is unwise to practice concentration or mind control, which takes years to give appreciable results.');
insert into guru.quote (workid,content) values (3,'The philosophy of positive thinking has to be replaced by the philosophy of positive Being.');
insert into guru.quote (workid,content) values (3,'The art of Being is necessarily the technique of first fathoming Being in the innermost level of one’s own life and then bringing It out from the transcendental field of unmanifested nature into the relative existence.');
insert into guru.quote (workid,content) values (3,'A technique or an art of something necessarily means that it should be done without strain and be accomplished thoroughly for greater advantage.');
insert into guru.quote (workid,content) values (3,'Being is the source of thinking. The process of thinking brings the mind out of the essential nature of its Being.');
insert into guru.quote (workid,content) values (3,'When with the practice of Transcendental Meditation the conscious mind fathoms the source of thought and becomes familiar with the state of Being, then the state of pure Being is so harmonious, blissful, and so pure in Its nature that the mind, having become familiar with It, will not part with It under any circumstances.');
insert into guru.quote (workid,content) values (3,'If the mind is without Being, the process of thinking is as though lifeless, and, when the mind is not familiar with Being, the process of thinking and the thought force are very weak. If these are weak, so will be the resultant activity, and, as a result of weak activity, the accomplishments are not satisfying and the fulfillment of life is not gained. So it is the art of Being while thinking that is the basis of all accomplishments and fulfillment in life.');
insert into guru.quote (workid,content) values (3,'It is breathing that lies between the individual being and cosmic Being,');
insert into guru.quote (workid,content) values (3,'The object coming in contact with the senses of experience leaves an impression of the object on the mind, and the essential nature of the mind of the experiencer is overshadowed.');
insert into guru.quote (workid,content) values (3,'This is how the cycle of experience, impression, desire—experience, impression, desire—continues to be, and the cycle of birth and death is thus continued.');
insert into guru.quote (workid,content) values (3,'because the nature of Being is absolute bliss consciousness, the mind becomes full with bliss consciousness, and everlasting happiness comes to the conscious level of the mind.');
insert into guru.quote (workid,content) values (3,'Such a mind is stable, unwavering, steady, and one-pointed, while it is also blissful, contented, self-contained, and sharp. The value of bringing the mind to the field of Being is that the mind becomes both sharp and contented, joyful and peaceful, at the same time.');
insert into guru.quote (workid,content) values (3,'senses receive their full contentment in bliss consciousness, and, even while experiencing the variety of joys of the objects, they are not bound by them');
insert into guru.quote (workid,content) values (3,'the practice of the art of Being on the level of the senses.');
insert into guru.quote (workid,content) values (3,'However, wandering is not the nature of the mind, and it is not necessary to control it in order to make it steady. It would be right to say that the nature of the mind is to remain steady.');
insert into guru.quote (workid,content) values (3,'There are saints in the Himalayas who live on life energy drawn from the atmosphere,');

insert into guru.work(id, name, author) values (4,'Breaking Free', 'Chett Vosloo');
insert into guru.quote (workid,content) values (4,'Anything you repeat over and over becomes a habit.');
insert into guru.quote (workid,content) values (4,'I had done this to myself.');
insert into guru.quote (workid,content) values (4,'Everything we experience mirrors back what is inside of us.');
insert into guru.quote (workid,content) values (4,'If watching the news was going to inspire me to make positive changes in my life, and to get out there and do good in the world, then fair enough. But it didn’t, so what was the point of taking in all that negativity?');
insert into guru.quote (workid,content) values (4,'Om Lokah Samastah Sukhino Bhavantu (may all beings be happy).');
insert into guru.quote (workid,content) values (4,'Om Namah Shivaya (I bow down to the Supreme Power).');
insert into guru.quote (workid,content) values (4,'And with this quiet mind I always enjoyed my walks so much more than when my mind was jabbering away.');
insert into guru.quote (workid,content) values (4,'I’d see a child playing, someone laughing, or even a couple holding hands, and I’d experience this great feeling of love inside me, as if I was the person who I was looking at.');
insert into guru.quote (workid,content) values (4,'A great Indian saint once said that if you own things and don’t use them, it’s the same as stealing.');
insert into guru.quote (workid,content) values (4,'Of the sixty countries I’ve traveled through to date, Iran has the warmest, most hospitable people of them all.');

insert into guru.work(id, name, author) values (5,'The Story of Tibet: Conversations with the Dalai Lama', 'Thomas Laird');
insert into guru.quote (workid,content) values (5,'The Dalai Lama spends four or five hours every day doing Buddhist meditation.');
insert into guru.quote (workid,content) values (5,'Meditation is not a philosophy; it is a technique to develop that type of attitude, detachment.”');
insert into guru.quote (workid,content) values (5,'Though agriculture later made its advent in Tibet, the society’s deep bond with nomadic cultures has never been broken, while Chinese farmers’ adversarial relations with the nomads of Inner Asia is just as deeply rooted.');
insert into guru.quote (workid,content) values (5,'The self or the consciousness, or mind, is beginning-less.');
insert into guru.quote (workid,content) values (5,'This law of causality,” he concluded, “is very similar to the scientific theory of evolution. Causes and conditions cause changes or evolution.”');
insert into guru.quote (workid,content) values (5,'The Jewel Ornament of Liberation helped to preserve the teachings of the yogi Milarepa in a book that is often compared to Atisha’s guide to the stages on the path, Lamp for the Path to Enlightenment.');

insert into guru.work(id, name, author) values (6,'The One-Straw Revolution: An Introduction to Natural Farming' ,'Masanobu Fukuoka');
insert into guru.quote (workid,content) values (6,'In an instant all my doubts and the gloomy mist of my confusion vanished. Everything I had held in firm conviction, everything upon which I had ordinarily relied was swept away with the wind. I felt that I understood just one thing. Without my thinking about them, words came from my mouth: "In this world there is nothing at all...." I felt that I understood nothing.');
insert into guru.quote (workid,content) values (6,'I could see that all the concepts to which I had been clinging, the very notion of existence itself, were empty fabrications.');
insert into guru.quote (workid,content) values (6,'Everything that had possessed me, all the agonies, disappeared like dreams and illusions, and something one might call "true nature" stood revealed.');
insert into guru.quote (workid,content) values (6,'To the extent that trees deviate from their natural form, pruning and insect extermination become necessary; to the extent that human society separates itself from a life close to nature, schooling becomes necessary. In nature, formal schooling has no function.');
insert into guru.quote (workid,content) values (6,'If even the names of plants are known, a mandarin orange tree of the citrus family, a pine of the pine family, nature is not seen in its true form. An object seen in isolation from the whole is not the real thing.');
insert into guru.quote (workid,content) values (6,'This is largely the result of returning to the soil everything grown in the field but the grain itself.');
insert into guru.quote (workid,content) values (6,'After six or seven years the citrus trees finally bore fruit.');
insert into guru.quote (workid,content) values (6,'With the green manure fertilizing the topsoil and the roots of the Morishima acacia improving the soil deep down, you can do quite well without fertilizer and there is no need to cultivate between the orchard trees. With tall trees for windbreaks, citrus in the middle, and a green manure cover below, I have found a way to take it easy and let the orchard manage itself.');
insert into guru.quote (workid,content) values (6,'Some people may be skeptical at first about using animal manure and human waste, thinking it primitive or dirty.');
insert into guru.quote (workid,content) values (6,'In growing vegetables in a "semi-wild" way, making use of a vacant lot, riverbank or open wasteland, my idea is to just toss out the seeds and let the vegetables grow up with the weeds. I grow my vegetables on the mountainside in the spaces between the citrus trees.');
insert into guru.quote (workid,content) values (6,'The important thing is knowing the right time to plant.');
insert into guru.quote (workid,content) values (6,'If various kinds of herbs and vegetables are mixed together and grown among the natural vegetation, damage by insects and diseases will be minimal');
insert into guru.quote (workid,content) values (6,'You can grow vegetables anyplace there is a varied and vigorous growth of weeds.');
insert into guru.quote (workid,content) values (6,'Since natural food can be produced with the least expense and effort, I reason that it should be sold at the cheapest price.');
insert into guru.quote (workid,content) values (6,'Extravagance of desire is the fundamental cause which has led the world into its present predicament.');
insert into guru.quote (workid,content) values (6,'Bodhidharma, the founder of Zen, spent');
insert into guru.quote (workid,content) values (6,'But actually, matter and mind are one.');
insert into guru.quote (workid,content) values (6,'By realizing "no-mind," without becoming lost in the subtleties of form, accepting the color of the colorless as color, right diet begins.');
insert into guru.quote (workid,content) values (6,'There is no other way than through the destruction of the ego, casting aside the thought that humans exist apart from heaven and earth.');
insert into guru.quote (workid,content) values (6,'In nature there is life and death, and nature is joyful. In human society there is life and death, and people live in sorrow.');
insert into guru.quote (workid,content) values (6,'the role of the scientist in society is analogous to the role of discrimination in your own minds."');
insert into guru.quote (workid,content) values (6,'make no promises, forget about yesterday, do not think about tomorrow, put sincere effort into each day''s work and leave no footprints here on earth.');

insert into guru.work(id, name, author) values (7,'The Tibetan Book Of Living And Dying', 'Sogyal Rinpoche');
insert into guru.quote (workid,content) values (7,'We obtain the blessing of aimless self-liberation of whatever arises.1');
insert into guru.quote (workid,content) values (7,'In fact, we are already perfectly trained by and for samsara,');
insert into guru.quote (workid,content) values (7,'that which we really are, our unchanging pure awareness,');
insert into guru.quote (workid,content) values (7,'It is like pouring a handful of sand onto a flat surface; each grain settles of its own accord.');
insert into guru.quote (workid,content) values (7,'“wisdom that realizes egolessness.”');
insert into guru.quote (workid,content) values (7,'wisdom and loving compassion radiate out from the mind’s innermost nature.');
insert into guru.quote (workid,content) values (7,'When you have this understanding, then rising thoughts only enhance your practice.');
insert into guru.quote (workid,content) values (7,'Become as resourceful in inspiring yourself to enter your own peace as you are at being neurotic and competitive in the world.');
insert into guru.quote (workid,content) values (7,'To embody the transcendent is why we are here.');
insert into guru.quote (workid,content) values (7,'Everything in my life went by for review—I was ashamed of a lot of the things I experienced because it seemed I had a different knowledge … Not only what I had done, but how I had affected other people … I found out that not even your thoughts are lost.20');
insert into guru.quote (workid,content) values (7,'I was the very people that I hurt, and I was the very people I helped to feel good.');
insert into guru.quote (workid,content) values (7,'whether I knew them or not …; plus the effect of each thought, word, and deed on weather, plants, animals, soil, trees, water, and air.');
insert into guru.quote (workid,content) values (7,'• the “natural” bardo of this life • the “painful” bardo of dying • the “luminous” bardo of dharmata • the “karmic” bardo of becoming');
insert into guru.quote (workid,content) values (7,'the true sky-like, primordial nature of our mind');
insert into guru.quote (workid,content) values (7,'The deeper our sensitivity and the more acute our alertness to the amazing opportunities for radical insight offered by gaps and transitions like these in life, the more inwardly prepared we will be for when they occur in an immensely more powerful and uncontrolled way at death.');
insert into guru.quote (workid,content) values (7,'Six realms of existence are identified in Buddhism: gods, demigods, humans, animals, hungry ghosts, and hells. They are each the result of one of the six main negative emotions: pride, jealousy, desire, ignorance, greed, and anger.');
insert into guru.quote (workid,content) values (7,'What we see is what our karmic vision allows us to see, and no more.');
insert into guru.quote (workid,content) values (7,'Pain, grief, loss, and ceaseless frustration of every kind are there for a real and dramatic purpose: to wake us up, to enable and almost to force us to break out of the cycle of samsara and so release our imprisoned splendor.');
insert into guru.quote (workid,content) values (7,'there are essentially three kinds of vision: the “impure, karmic vision” of ordinary beings; the “vision of experience,” which opens to practitioners in meditation and is the path or medium of transcendence; and the “pure vision” of realized beings. A realized being, or a buddha, will perceive this world as spontaneously perfect, a completely and dazzlingly pure realm. Since they have purified all the causes of karmic vision, they see everything directly in its naked, primordial sacredness.');
insert into guru.quote (workid,content) values (7,'If the doors of perception were cleansed, Everything would appear … as it is, infinite.');
insert into guru.quote (workid,content) values (7,'Enter, undistracted, the path of listening and hearing, reflection and contemplation, and meditation,');
insert into guru.quote (workid,content) values (7,'Making perceptions and mind the path, and realize the “three kayas”: the enlightened mind;');
insert into guru.quote (workid,content) values (7,'So ego, then, is the absence of true knowledge of who we really are, together with its result: a doomed clutching on, at all costs, to a cobbled together and makeshift image of ourselves, an inevitably chameleon charlatan self that keeps changing and has to, to keep alive the fiction of its existence.');
insert into guru.quote (workid,content) values (7,'Tertön Sogyal, the Tibetan mystic, said that he was not really impressed by someone who could turn the floor into the ceiling or fire into water. A real miracle, he said, was if someone could liberate just one negative emotion.');
insert into guru.quote (workid,content) values (7,'Go to a quiet place and rob all your perceptions, and steal all the stars and planets in the sky, and dissolve them into the belly of emptiness, the all-encompassing space of the nature of mind.”');
insert into guru.quote (workid,content) values (7,'“Do not mistake understanding for realization, and do not mistake realization for liberation.”');
insert into guru.quote (workid,content) values (7,'NO ONE CAN die fearlessly and in complete security until they have truly realized the nature of mind. For only this realization, deepened over years of sustained practice, can keep the mind stable during the molten chaos of the process of death. Of all the ways I know of helping people to realize the nature of mind, that of the practice of Dzogchen, the most ancient and direct stream of wisdom within the teachings of Buddhism, and the source of the bardo teachings themselves, is the clearest, most effective, and most relevant to the environment and needs of today.');
insert into guru.quote (workid,content) values (7,'My life, my teachings, and this book are dedicated to lighting this fire in the hearts and minds of the world.');
insert into guru.quote (workid,content) values (7,'All the Buddhist teachings are explained in terms of “Ground, Path, and Fruition.”');
insert into guru.quote (workid,content) values (7,'the mind’s restless hunger for thinking and research, and its dependence on endless conceptualizing, analysis, and references,');
insert into guru.quote (workid,content) values (7,'“Your deadliest enemies, the ones who have kept you tied to samsara through countless lives from beginningless time up until the present, are the grasping and the grasped.”');
insert into guru.quote (workid,content) values (7,'“Meditation consists of being attentive to such a state of Rigpa, free from all mental constructions, whilst remaining fully relaxed, without any distraction or grasping.');
insert into guru.quote (workid,content) values (7,'The ordinary, habitual mind with its projections is extremely powerful. It keeps returning, and takes hold of us easily when we are inattentive or distracted.');
insert into guru.quote (workid,content) values (7,'The essence of meditation practice in Dzogchen is encapsulated by these four points:');
insert into guru.quote (workid,content) values (7,'strong emotions come, like anger, desire, jealousy. The real practitioner recognizes them not as a disturbance or obstacle, but as a great opportunity.');
insert into guru.quote (workid,content) values (7,'see right through them as soon as they arise, to what they really are: the vivid and electric manifestation of the energy of Rigpa itself.');
insert into guru.quote (workid,content) values (7,'Dzogchen entails an extreme risk.');
insert into guru.quote (workid,content) values (7,'You chuckle from inside as you see the façade of samsara and nirvana;');
insert into guru.quote (workid,content) values (7,'The heart of the Dzogchen training is two practices, Trekchö and Tögal,');
insert into guru.quote (workid,content) values (7,'We all long for heaven where God is, but we have it in our power to be in heaven with Him at this very moment. But being happy with Him now means: Loving as He loves, Helping as He helps, Giving as He gives, Serving as He serves, Rescuing as He rescues, Being with Him twenty-four hours, Touching Him in his distressing disguise.');
insert into guru.quote (workid,content) values (7,'it could be forgiveness, purification, dedication, or feeling the presence of light or love.');
insert into guru.quote (workid,content) values (7,'It is said that “medium practitioners of middling capacity die like wild animals or lions, on snow mountains, in mountain caves and empty valleys.” They can take care of themselves completely and prefer to go to deserted places and die quietly, without being disturbed or fussed over by friends and relatives.');
insert into guru.quote (workid,content) values (7,'the transmutation of desire, the predominant emotion of the human realm.');
insert into guru.quote (workid,content) values (7,'The essential phowa practice I have explained in the previous chapter is as much a healing practice for the living as a practice for the moment of death, and can be done at any time without danger. However, the timing of the traditional phowa practice is of paramount importance.');
insert into guru.quote (workid,content) values (7,'Do nothing but practice, so that it even continues in your dreams.');
insert into guru.quote (workid,content) values (7,'The deepening perception of the body’s illusory nature is one of the most profound and inspiring realizations we can have to help us to let go.');
insert into guru.quote (workid,content) values (7,'to die when we die,');
insert into guru.quote (workid,content) values (7,'Stripped of a physical body, mind stands naked, revealed startlingly for what it has always been: the architect of our reality.');
insert into guru.quote (workid,content) values (7,'we can recognize.');
insert into guru.quote (workid,content) values (7,'This power to attain stability by just recognizing the nature of mind is like a torch which in one instant can clear away the darkness of eons.');
insert into guru.quote (workid,content) values (7,'When we suddenly realize that our whole life, our whole reality, is disappearing, it is terrifying: We don’t know what is happening to us, or where we are going. Nothing in our previous experience has prepared us for this. As anyone who has cared for the dying will know, our anxiety will even heighten the experience of physical pain.');
insert into guru.quote (workid,content) values (7,'For good practitioners who know exactly what is happening, not only is death less painful and fearful but it is the very moment they have been looking forward to; they face it with equanimity, and even with joy.');
insert into guru.quote (workid,content) values (7,'by directing his or her mind to any particular point in the body, a practitioner can bring the winds there.');
insert into guru.quote (workid,content) values (7,'all the thought states resulting from anger, thirty-three of them in all, come to an end.');
insert into guru.quote (workid,content) values (7,'there arises a great experience of bliss, as all the thought states resulting from desire, forty in all, cease to function.');
insert into guru.quote (workid,content) values (7,'The three “poisons”—anger, desire, and ignorance—all die, which means that all the negative emotions, the root of samsara, actually cease, and then there is a gap.');
insert into guru.quote (workid,content) values (7,'As anger, desire, and ignorance are dying,');
insert into guru.quote (workid,content) values (7,'As everything that obscures the nature of mind is dying,');
insert into guru.quote (workid,content) values (7,'the Tantric practitioner prepares in life for the process of dying, by simulating the changes of consciousness of the dissolution process,');
insert into guru.quote (workid,content) values (7,'It also occurs, usually unnoticed, as we fall asleep, or');
insert into guru.quote (workid,content) values (7,'it also happens in the very psychological processes of our everyday waking state.10');
insert into guru.quote (workid,content) values (7,'a gradual development and dawning of ever more subtle levels of consciousness. Each one emerges upon the successive dissolution of the constituents of body and mind,');
insert into guru.quote (workid,content) values (7,'So the five negative emotions arise as the direct result of our not recognizing their true nature. When truly recognized, they are purified and liberated, and arise themselves as none other than the display of the five wisdoms.');
insert into guru.quote (workid,content) values (7,'whenever self-grasping arises it solidifies both our inner experience and the way we perceive the world around us.');
insert into guru.quote (workid,content) values (7,'arising negative emotions start to solidify into different false perceptions,');
insert into guru.quote (workid,content) values (7,'The whole of spiritual practice, then, is dedicated to directly reversing what I would call this progress of ignorance, and so of de-creating, de-solidifying those interlinked and interdependent false perceptions that have led to our entrapment in the illusory reality of our own invention.');
insert into guru.quote (workid,content) values (7,'Through training in creating and reabsorbing the deities in the practice of visualization, he or she realizes that the mind that perceives the deity and the deity itself are not separate.');
insert into guru.quote (workid,content) values (7,'Think how almost impossible it is to remember something like a prayer in a dream or nightmare, how impotent and powerless we feel in them; in the bardo of becoming it is just as hard, if not harder, to collect our thoughts at all.');
insert into guru.quote (workid,content) values (7,'abandon the emotions such as desire, anger, or jealousy, and recognize that none of these bardo experiences have any ultimate reality. If you can realize this and then rest the mind in its true, empty nature,');
insert into guru.quote (workid,content) values (7,'So the seed of the hell realm and its cause, anger, are located at the soles of the feet; the hungry ghost realm and its cause, avarice, rest at the base of the trunk; the animal realm and its cause, ignorance, rest at the navel; the human realm and its cause, doubt, rest at the heart; the demigod realm and its cause, jealousy, rest at the throat; and the god realm and its cause, pride, rest at the crown of the head.');
insert into guru.quote (workid,content) values (7,'As Rilke wrote, the protected heart that is “never exposed to loss, innocent and secure, cannot know tenderness; only the won-back heart can ever be satisfied: free, through all it has given up, to rejoice in its mastery.”');
insert into guru.quote (workid,content) values (7,'I wonder if this threefold process the bardos reveal is true not only, as we discovered, of all the different levels of consciousness and of all the different experiences of consciousness, both in life and death, but also perhaps of the actual nature of the universe itself.');
insert into guru.quote (workid,content) values (7,'But that change must begin with the individual;');
insert into guru.quote (workid,content) values (7,'As the Buddha said: “I have shown you the way to liberation, now you must take it for yourself.”');
insert into guru.quote (workid,content) values (7,'Thich Nhat Hanh, Old Path, White Clouds (Berkeley, CA: Parallax Press, 1991), 121.');
insert into guru.quote (workid,content) values (7,'The three kayas are the three aspects of the true nature of mind described in Chapter 4: its empty essence, radiant nature, and all-pervasive energy; see also Chapter 21, “The Universal Process.”');

insert into guru.work(id, name, author) values (9,'The Presence Process - A Journey Into Present Moment Awareness', 'Michael Brown');
insert into guru.quote (workid,content) values (9,'As we approach present moment awareness, we perceive that the world in front of us right now is asking, in the only way it knows how, for unconditional love. So also are we. The world mirrors our plight.');
insert into guru.quote (workid,content) values (9,'...commences with the act of giving unto ourselves that which we are seeking from others.');
insert into guru.quote (workid,content) values (9,'...energy trapped in a holding pattern of continual resistance.');
insert into guru.quote (workid,content) values (9,'This observation begins as an energetic felt-perception, then becomes conceptual, and next circumstantial.');
insert into guru.quote (workid,content) values (9,'We then identify with this uncomfortable resonance to the point we can’t perceive it as something apart from us.');
insert into guru.quote (workid,content) values (9,'We use the consequences of our attempts at intimate relationships to discover what our unconscious definition of love is.');
insert into guru.quote (workid,content) values (9,'...the resonance of the emotional signature');
insert into guru.quote (workid,content) values (9,'...we therefore consciously and unconsciously manipulate every experience in an attempt to recreate the resonance of the emotional charge');
insert into guru.quote (workid,content) values (9,'Releasing ourselves from lack and entering into unlimited abundance commences when we give unconditionally to ourselves that which we have been seeking from others: unconditional attention.');
insert into guru.quote (workid,content) values (9,'There is no love to “get” in the world either. The world is as neutral as a mirror. We perceive in it what we place before it. When we attempt to get love from this world by taking it, we steer our experience deeper and deeper into lack.');
insert into guru.quote (workid,content) values (9,'The energetic conditions imprinted in our emotional body during childhood are the conditions we have come into this life to overcome because they are what prevent us from experiencing unconditional love.');
insert into guru.quote (workid,content) values (9,'...cause and effect states that we perceive what we are looking for.');
insert into guru.quote (workid,content) values (9,'As long as we are unable to wield felt-perception to connect with Presence in ourselves, we struggle to connect with Presence in others. Consequently, we don’t realize we are one body, one mental matrix, one heart, and one vibrational essence.');
insert into guru.quote (workid,content) values (9,'The mental body believes free will is the capacity to function separately from the whole. This is as deluded as thinking one may determine the course of a river by floating down it. In the human body, when a cell behaves this way, we call it cancer. When a human behaves this way, we call it “ambition” or “capitalism.”');
insert into guru.quote (workid,content) values (9,'Through increased present moment awareness, we experience an aspect of our being that remains unchanged no matter what. Our immortality therefore dawns on us as an authentic “knowing.”');
insert into guru.quote (workid,content) values (9,'Our source ceases to be a personality, limited by our religious imprinting.');

insert into guru.work(id, name, author) values (10,'Out of Your Mind (youtube)', 'Alan Watts');
insert into guru.quote (workid,content) values (10,'When one speaks of awakening it means de-hynotization, coming to your senses.  But of course to do that you have to go out of your mind.');

insert into guru.work(id, name, author) values (13,'', 'Unknown');
insert into guru.quote (workid,content) values (13,'The thralldom of desire, the burden of fear.');
insert into guru.quote (workid,content) values (13,'As we approach present moment awareness, we perceive that the world in front of us right now is asking, in the only way it knows how, for unconditional love. So also are we. The world mirrors our plight.');
insert into guru.quote (workid,content) values (13,'Count your blessings.  List three every day.');

insert into guru.work(id, name, author) values (14,'The Cosmic Law (youtube)','Ramesh Balsekar');
insert into guru.quote (workid,content) values (14,'Don''t blame yourself.  Don''t blame anyone else.  No guilt, shame, hatred, anger.');
insert into guru.quote (workid,content) values (14,'Nothing can happen that is not God''s will.');
insert into guru.quote (workid,content) values (14,'You cannot make a mistake.  You cannot commit a sin.');

insert into guru.work(id, name, author) values (15,'Sleeping, Dreaming, and Dying', 'Dalai Lama');
insert into guru.quote (workid,content) values (15,'Without an enemy, you cannot learn patience and tolerance.');
insert into guru.quote (workid,content) values (15,'I say "spiritual" without meaning any particular religion or faith, just simple warmhearted compassion, human affection, and gentleness.');
insert into guru.quote (workid,content) values (15,'But there are phases of both Buddhist and non-Buddhist meditative practice during which effort is utterly suspended. One example of that is in the practice of Dzogchen, or the Great Perfection. This entails a very special kind of suspension of effort. There’s another practice common to Buddhists and non-Buddhists, in which you simply abide in equanimity. But that is different from the suspension of effort in the Buddhist practice of Dzogchen.');
insert into guru.quote (workid,content) values (15,'Actually there are two senses of the self, one gross and one subtle. The gross sense of self arises in dependence upon this gross physical body. But when one experiences the subtle sense of self, the gross body becomes irrelevant, and fear of losing one’s self vanishes.');

insert into guru.work (id, name, author) values(16,'The End, Abbey Road', 'The Beatles');
insert into guru.quote (workid,content) values (16,'And in the end, the love you take is equal to the love you make.');

insert into guru.work (id, name, author) values(17,'American Beauty 1999', 'Alan Ball');
insert into guru.quote (workid,content) values (17,'That''s the day I realized that there was this entire life behind things and this incredibly benevolent force that wanted me to know that there was no reason to be afraid ever.');
insert into guru.quote (workid,content) values (17,'Sometimes there''s so much beauty in the world. I feel like I can''t take it and my heart is just going to cave in.');

insert into guru.work (id, name, author) values(18,'https://www.youtube.com/watch?v=BI2vBONcMj8 [20:50]', 'Elon Musk');
insert into guru.quote (workid,content) values (18,'When I was a teenager I was trying to figure out what is the meaning of life and there doesn''t seem to be any good answer.  In the absence of having a good answer then we should try to expand the scope and scale of human consciousness in order to better appreciate the nature of the problem that we''re trying to solve and figure out which questions to ask.  Like in the Hitchhikers Guide to the Galaxy, Douglas Adams hits the nail on the head that the tough part is figuring out which questions to ask. Once you have a properly formatted question, finding the answer is comparatively easy.  So if we''re going to do that then we obviously want to maximize the likely lifespan of humanity and expand beyond earth and get a better understanding of the universe.');

insert into guru.work (id, name, author) values(19,'', 'Amma');
insert into guru.quote (workid,content) values (19,'India has given three great teachings to the world: 1. If we protect dharma, dharma will protect us. It will protect the whole world. This is the first teaching.  2. Whatever action we undertake, it should be done for the benefit of the whole world.  It should be done as an offering to God.’  This mental attitude of selfless offering should be underlying all our actions. That is the second teaching.  3. Everything is an expression of the one Atman. No one is separate from us.  God pervades all of creation.  This is the third teaching.  If we are able to imbibe these teachings in our lives, it will bring about an end to all wars.  Peace and contentment will spread throughout the world.  We will be able to experience supreme peace and bliss in our lives.  We will become a source of light to all others.');

insert into guru.work (id, name, author) values(20,'', 'Hippocrates');
insert into guru.quote (workid,content) values (20,'Let food be thy medicine and medicine be thy food.');
insert into guru.quote (workid,content) values (20,'All disease begins in the gut.');

insert into guru.work(id, name, author) values (21,'youtube', 'Sadhguru');
insert into guru.quote (workid,content) values (21,'Both space and time is a creation of the conscious mind. If you transcend the limits of the conscious mind then there is no such thing as space and time.');
insert into guru.quote (workid,content) values (21,'The philosopher fish. Cannot find the ocean. You are looking for divinity and cannot find it. Because it is part of you. You are breathing it, eating it, walking on it.');
insert into guru.quote (workid,content) values (21,'As soon as you have experienced everything and everyone as part of yourself, nobody has to tell you how you should live here.');
insert into guru.quote (workid,content) values (21,'The limitations of sense perception.');
insert into guru.quote (workid,content) values (21,'You are identified with things you are not. Once your entire existence is rooted in the memory you have gathered, you will invariably be a compulsive thought process. Once you are in a haze of compulsive thought process, you cannot conduct anything consciously.');

insert into guru.work(id, name, author) values (22,'youtube', 'Byron Katie');
insert into guru.quote (workid,content) values (22,'We are not special people, we are everyone.  We are everyone, no exceptions.  There is no one and nothing that is not a blessing in your life, a gift.');
insert into guru.quote (workid,content) values (22,'I don''t have control.  None.  That works for me because I understand the universe is friendly.  I understand our true nature.');
insert into guru.quote (workid,content) values (22,'We see images in our head.  We put a story on it.  We believe it.  That is this false identity that we wear, that we believe ourselves to be.');
insert into guru.quote (workid,content) values (22,'There is nothing in this world that is not specifically for you, here to serve you and only you, and it is beautiful.');
insert into guru.quote (workid,content) values (22,'There are no new thoughts.  They are all recycled.  I want... I need... You should... I don''t want to... I''m angry.');

insert into guru.work(id, name, author) values (23,'Vulture Peak', 'John Burdett');
insert into guru.quote (workid,content) values (23,'When you think you are looking into the first nanoseconds of the Big Bang, what you are really looking at is the way your own mind works, because that’s the only thing the mind can ever discover: itself. ');
insert into guru.quote (workid,content) values (23,'Bottom line: the cosmos is an expression of loving kindness; but even symmetry is subject to the law of symmetry. You can’t have it without its opposite: asymmetry. It’s the law of opposites, good for everything this side of cosmic consciousness. ');
insert into guru.quote (workid,content) values (23,'Once you know the rule, you are no longer surprised by the antics of your head in its unending quest for a smooth ride and a free lunch.');
